// export const AUTH_URL = "https://recruiterjobs.online/api/v1/auth/"
// export const ADMIN_URL = "https://recruiterjobs.online/api/v1/admin/"
// export const USER_SERVICE = "https://recruiterjobs.online/api/v1/user/"
// export const JOBS_SERVICE = "https://recruiterjobs.online/api/v1/jobs/"
// export const PUBLIC_JOBS = "https://recruiterjobs.online/api/v1/publicJobs/"

export const AUTH_URL = "http://localhost:8765/api/v1/auth/"
export const ADMIN_URL = "http://localhost:8765/api/v1/admin/"
export const USER_SERVICE = "http://localhost:8765/api/v1/user/"
export const JOBS_SERVICE = "http://localhost:8765/api/v1/jobs/"
export const PUBLIC_JOBS = "http://localhost:8765/api/v1/publicJobs/"